module.exports = [
    { action: '\\sqrt', label: '\\sqrt{X}' },
    { action: '^', label: 'x^{X}' },
    { action: '\\frac', label: '\\frac{X}{X}' },
    { action: '\\int', label: '\\int_{X}^{X}' },
    { action: '\\neq', label: '\\neq' },
    { action: '\\lim_', label: '\\lim_{X}' },
    { action: '\\to', label: '\\to' },
    { action: '\\overrightarrow', label: '\\overrightarrow{X}' },
    { action: '_', label: 'x_X' },
    { action: '\\nthroot', label: '\\sqrt[X]{X}' },
    { action: '\\sum', label: '\\sum_{X}^{X}' },
    { action: '\\binom', label: '\\binom{X}{X}' },
    { action: '\\sin' },
    { action: '\\cos' },
    { action: '\\tan' },
    { action: '\\arcsin' },
    { action: '\\arccos' },
    { action: '\\arctan' },
    { action: '\\le' },
    { action: '\\ge' },
    { action: '\\approx' },
    { action: '\\not' },
    { action: '\\pm' },
    { action: '\\in' },
    { action: '\\ni' },
    { action: '\\cdot' },
    { action: '\\parallel' },
    { action: '\\pi' },
    { action: '\\vec', label: '\\vec{X}' },
    { action: '\\bar', label: '\\bar{X}' },
    { action: '\\underline', label: '\\underline{X}' },
    { action: '\\overleftarrow', label: '\\overleftarrow{X}' },
    { action: '\\times' },
    { action: '\\mp' },
    { action: '\\notin' },
    { action: '\\div' },
    { action: '\\subset' },
    { action: '\\cap' },
    { action: '\\cup' },
    { action: '\\equiv' },
    { action: '\\sim' },
    { action: '\\cong' },
    { action: '\\infty' },
    { action: '\\varnothing' },
    { action: '\\pi' },
    { action: '\\wedge' },
    { action: '\\vee' },
    { action: '\\forall' },
    { action: '\\exists' },
    { action: '\\nexists' },
    { action: '\\angle' },
    { action: '\\bot' },
    { action: '\\triangle' },
    { action: '\\leftarrow' },
    { action: '\\Leftarrow' },
    { action: '\\rightarrow' },
    { action: '\\Rightarrow' },
    { action: '\\Leftrightarrow' },
    { action: '\\uparrow' },
    { action: '\\downarrow' },
    { action: '\\circ' },
    { action: '|', label: '|X|'},
    { action: '(', label: '(X)'},
    { action: '\\setminus' }
]
