module.exports = [
    {action: '\\sqrt', label: '\\sqrt{X}'},
    {action: '^', label: 'X^{X}'},
    {action: '\\frac', label: '\\frac{X}{X}'},
    {action: '\\int', label: '\\int_{X}^{X}'},
    {action: '\\neq', label: '\\neq'},
    {action: '\\lim_', label: '\\lim_{X}'},
    {action: '\\to', label: '\\to'},
    {action: '\\overrightarrow', label: '\\overrightarrow{X}'},
    {action: '_', label: 'X_X'},
    {action: '\\nthroot', label: '\\sqrt[X]{X}'},
    {action: '\\sum'},
    {action: '\\binom', label: '\\binom{X}{X}'},
    {action: '\\sin'},
    {action: '\\cos'},
    {action: '\\tan'},
    {action: '\\arcsin'},
    {action: '\\arccos'},
    {action: '\\arctan'},
    {action: '\\le'},
    {action: '\\ge'},
    {action: '\\approx'},
    {action: '\\not'},
    {action: '\\pm'},
    {action: '\\in'},
    {action: '\\ni'},
    {action: '\\cdot'},
    {action: '\\parallel'},
    {action: '\\pi'},
    {action: '\\vec', label: '\\vec{X}'},
    {action: '\\bar', label: '\\bar{X}'},
    {action: '\\overleftarrow', label: '\\overleftarrow{X}'},
    {action: '\\hat', label: '\\hat{X}'},
]
