module.exports = [
    {character: '°'},
    {character: '≡', latexCommand: '\\equiv'},
    {character: '≢'}, // \nequiv or \not\equiv
    {character: '≈', latexCommand: '\\approx'},
    {character: '∼', latexCommand: '\\sim'},
    {character: '≠', latexCommand: '\\neq'},
    {character: '≤', latexCommand: '\\leq'},
    {character: '≥', latexCommand: '\\geq'},
    {character: '×', latexCommand: '\\times'},
    {character: '÷', latexCommand: '\\div'},
    {character: '·', latexCommand: '\\cdot'},
    {character: '…', latexCommand: '\\dots'},
    {character: '¹', latexCommand: '^1'},
    {character: '²', latexCommand: '^2'},
    {character: '³', latexCommand: '^3'},
    {character: '½', latexCommand: '1/2'},
    {character: '←', latexCommand: '\\leftarrow'},
    {character: '↑', latexCommand: '\\uparrow'},
    {character: '→', latexCommand: '\\rightarrow'},
    {character: '↓', latexCommand: '\\downarrow'},
    {character: '↔', latexCommand: '\\leftrightarrow'},
    {character: '⇒', latexCommand: '\\Rightarrow'},
    {character: '⇔', latexCommand: '\\Leftrightarrow'},
    {character: '⇌'}, // \rightleftharpoons
    {character: '∞', latexCommand: '\\infty'},
    {character: '±', latexCommand: '\\pm'},
    {character: '∠', latexCommand: '\\angle'},
    {character: '△', latexCommand: '\\triangle'},
    {character: '⊥', latexCommand: '\\perp'},
    {character: '‖', latexCommand: '\\parallel'},
    {character: '∘', latexCommand: '\\circ'},

    {character: 'µ', latexCommand: '\\mu'},
    {character: '∂', latexCommand: '\\partial'},
    {character: '∑', latexCommand: '\\Sigma'},
    {character: '∏', latexCommand: '\\Pi'},
    {character: 'Ω', latexCommand: '\\Omega'},
    {character: 'Δ', latexCommand: '\\Delta'},
    {character: '𝜄', latexCommand: '\\iota'},
    {character: 'Ð'}, // \Eth
    {character: 'ð'}, // \eth
    {character: 'Þ'}, // \thorn
    {character: 'þ'}, // \Thorn
    {character: 'Γ', latexCommand: '\\Gamma'},
    {character: 'Θ', latexCommand: '\\Theta'},
    {character: 'Φ', latexCommand: '\\Phi'},
    {character: 'η', latexCommand: '\\eta'},
    {character: 'α', latexCommand: '\\alpha'},
    {character: 'δ', latexCommand: '\\delta'},
    {character: 'ε', latexCommand: '\\varepsilon'},
    {character: 'σ', latexCommand: '\\sigma'},
    {character: 'τ', latexCommand: '\\tau'},
    {character: 'Ω', latexCommand: '\\Omega'},
    {character: 'ω', latexCommand: '\\omega'},
    {character: 'Д'}, // \cyrd
    {character: 'π', latexCommand: '\\pi'},
    {character: 'Ф', latexCommand: '\\phi'},

    {character: '∈', latexCommand: '\\in'},
    {character: '∉', latexCommand: '\\notin'},
    {character: '∋', latexCommand: '\\ni'},
    {character: 'ℝ'},
    {character: 'ℕ'},
    {character: 'ℤ'},
    {character: 'ℚ'},
    {character: 'ℂ'},
    {character: '⊂', latexCommand: '\\subset'},
    {character: '⊃', latexCommand: '\\supset'},
    {character: '∩', latexCommand: '\\cap'},
    {character: '∪', latexCommand: '\\cup'},
    {character: '∅', latexCommand: '\\empty'},
    {character: '∖', latexCommand: '\\setminus'},

    {character: '⌐'}, // \backneg
    {character: '∧', latexCommand: '\\and'},
    {character: '∨', latexCommand: '\\or'},
    {character: '∀', latexCommand: '\\forall'},
    {character: '∃', latexCommand: '\\exists'}
]
